{% set name = "streamad" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamad-{{ version }}.tar.gz
  sha256: 47301534198e8e9aa37cd28cc61fe74594ca58688b5062479d645956b286fa00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.13
    - pandas >=0.25
    - python
    - scikit-learn >=0.19.1
    - scipy >=0.19.1

test:
  imports:
    - streamad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fengrui-Liu/StreamAD
  summary: Online anomaly detection for streaming data.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Fengrui-Liu
